name: Build and deploy

on:
  push:
    branches:
      - main

concurrency:
  group: ci-${{ github.event.client_payload.branch || github.ref_name }}
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger update script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          fingerprint: ${{ secrets.DEPLOY_FINGERPRINT }}
